# Generated by Django 5.2 on 2025-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RubrosApp', '0002_remove_rubrocat_imagen_alter_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='alias',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Short Alias'),
        ),
    ]
