"""
Django settings for NovaraRey project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# CONFIGURACIÓN DE ENTORNO
# ==============================================================================

# Detectar si estamos en desarrollo o producción
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

# Secret Key - En producción debe venir de variable de entorno
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_b*ure!#bjw76t-@p5co4t^lr71^814fqlmen1tp*#%&e0#_m1')

# Hosts permitidos
if DEBUG:
    ALLOWED_HOSTS = ['imendiola.pythonanywhere.com', '127.0.0.1', 'localhost']
else:
    ALLOWED_HOSTS = ['imendiola.pythonanywhere.com']

# ==============================================================================
# APLICACIONES
# ==============================================================================

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Para formatear números, fechas, etc.
]

THIRD_PARTY_APPS = [
    'crispy_forms',
    'crispy_bootstrap4',
]

LOCAL_APPS = [
    'MainApp',
    'RubrosApp',
    'AseguradoraApp',
    'AuthApp',
    'StaffApp',
    'ClientesApp',
    'CotizacionesApp',
    'ProductorApp',
    'EmisionesApp',
    'ContadoApp',
    'SiniestrosApp',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ==============================================================================
# MIDDLEWARE
# ==============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Para i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NovaraRey.urls'

# ==============================================================================
# TEMPLATES
# ==============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Carpeta global de templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Para acceder a MEDIA_URL en templates
            ],
        },
    },
]

WSGI_APPLICATION = 'NovaraRey.wsgi.application'

# ==============================================================================
# BASE DE DATOS
# ==============================================================================

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # MySQL para producción en PythonAnywhere
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'imendiola$novarareydb'),  # Formato típico de PythonAnywhere
            'USER': os.getenv('DB_USER', 'imendiola'),
            'PASSWORD': os.getenv('DB_PASSWORD'),  # DEBE ser configurada como variable de entorno
            'HOST': os.getenv('DB_HOST', 'imendiola.mysql.pythonanywhere-services.com'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'isolation_level': 'read committed',
            },
        }
    }

# ==============================================================================
# VALIDACIÓN DE CONTRASEÑAS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Mínimo 8 caracteres
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==============================================================================
# INTERNACIONALIZACIÓN
# ==============================================================================

LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Idiomas disponibles (si planeas multiidioma en el futuro)
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# ==============================================================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ==============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Para producción

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / "media"

# ==============================================================================
# CONFIGURACIÓN DE FORMULARIOS
# ==============================================================================

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# ==============================================================================
# AUTENTICACIÓN Y SESIONES
# ==============================================================================

LOGIN_URL = '/login/login'
LOGIN_REDIRECT_URL = '/staff/'  # Redirigir staff después del login
LOGOUT_REDIRECT_URL = '/'  # Redirigir a home después del logout

# Configuración de sesiones
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD
# ==============================================================================

# Configuraciones de seguridad para producción
if not DEBUG:
    # HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookies seguras
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Headers de seguridad
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ==============================================================================
# LOGGING
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logs específicos de tu aplicación
        'NovaraRey': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# ==============================================================================
# CONFIGURACIONES ESPECÍFICAS DEL NEGOCIO
# ==============================================================================

# Configuraciones para seguros (puedes expandir según necesites)
SEGUROS_SETTINGS = {
    'DIAS_AVISO_VENCIMIENTO_POLIZA': 30,
    'DIAS_AVISO_CUMPLE_CLIENTE': 15,
    'MONEDA_DEFAULT': 'ARS',
    'FORMATO_FECHA_ARGENTINA': '%d/%m/%Y',
}

# ==============================================================================
# CONFIGURACIONES DE EMAIL (para futuras notificaciones)
# ==============================================================================

if DEBUG:
    # En desarrollo, mostrar emails en consola
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # En producción, configurar SMTP real
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@novararey.com')

# ==============================================================================
# CONFIGURACIONES ADICIONALES
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Tamaño máximo de archivos subidos (en bytes) - 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Formatos de fecha y hora para Argentina
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
SHORT_DATE_FORMAT = 'd/m/Y'

# Cache (para desarrollo usar dummy, en producción Redis/Memcached)
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        }
    }




# ----------------------
# S3 Storage Settings
# ----------------------

# Configuración de AWS S3
AWS_ACCESS_KEY_ID = 'AKIA4SMLJMGVLXJHEMLX'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'storage-novara-rey'
AWS_S3_REGION_NAME = 'us-east-2'

# IMPORTANTE: Desactivar ACLs para buckets que no las soportan
AWS_DEFAULT_ACL = 'public-read'  # Cambiar de 'public-read' a None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# Configuración adicional
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_LOCATION = ''  # ruta base en el bucket

# Configuración de storages
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "default_acl": 'public-read' ,  # Importante: desactivar ACLs
            "querystring_auth": AWS_QUERYSTRING_AUTH,
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
            "location": AWS_LOCATION,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }
}