# Generated by Django 5.2 on 2025-06-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmisionesApp', '0010_emision_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.IntegerField(verbose_name='Cantidad de cuotas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='A', max_length=1, verbose_name='Estado')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pagos', to='EmisionesApp.poliza', verbose_name='Póliza')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.IntegerField(verbose_name='Nro de cuota')),
                ('vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('G', 'Pagado'), ('A', 'Anulado')], default='P', max_length=1, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('plan_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ContadoApp.planpagos', verbose_name='Plan de pagos')),
            ],
        ),
    ]
