# Generated by Django 5.2 on 2025-05-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de dirección')),
            ],
            options={
                'verbose_name': 'Tipo de dirección',
                'verbose_name_plural': 'Tipos de dirección',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso')),
                ('dpto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dpto')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.adresstype', verbose_name='Tipo de dirección')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
