# Generated by Django 5.2 on 2025-06-20 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cp',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Ingrese un código postal válido', regex='^[A-Z]?\\d{4}[A-Z]{0,3}$')], verbose_name='Código Postal'),
        ),
    ]
