# Generated by Django 5.2 on 2025-06-17 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CotizacionesApp', '0013_remove_cotizacion_sujeto_cotizacion_extradata_and_more'),
        ('ProductorApp', '0003_codigoproductor_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('aceptacion', models.FileField(blank=True, null=True, upload_to='aceptaciones/', verbose_name='Archivos de aceptación del Cliente')),
                ('extradata', models.TextField(blank=True, null=True, verbose_name='Datos extra')),
                ('poliza', models.BooleanField(default=False, verbose_name='Tiene Poliza')),
                ('Cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CotizacionesApp.cotizacion', verbose_name='Cotización')),
                ('cod_prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductorApp.codigoproductor')),
                ('cot_cia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CotizacionesApp.cotizacioncia', verbose_name='Cotizacion de la compañia')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuevas_emisiones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
        ),
        migrations.CreateModel(
            name='DocEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='filesEmisiones/', verbose_name='Archivos asociados a emisiones')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripción del Archivo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuevo_doc_emision', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmisionesApp.emision', verbose_name='Emisión')),
            ],
        ),
    ]
