# Generated by Django 5.2 on 2025-06-18 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0003_mediopago_tarjetacredito_transferenciabancaria'),
        ('EmisionesApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='emision',
            old_name='poliza',
            new_name='tiene_poliza',
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('numero', models.CharField(max_length=20, verbose_name='Número de POliza')),
                ('refacturacion', models.CharField(choices=[('M', 'Mensual'), ('BM', 'Bimestral'), ('TM', 'Trimestral'), ('CM', 'Cuatrimestral'), ('SM', 'Semestral'), ('A', 'Anual')], max_length=2, verbose_name='Período de refacturación')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('rel_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmisionesApp.emision', verbose_name='Emisión')),
                ('rel_medio_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClientesApp.mediopago', verbose_name='Emisión')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nueva_poliza', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
        ),
    ]
