# Generated by Django 5.2 on 2025-06-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmisionesApp', '0002_rename_poliza_emision_tiene_poliza_poliza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emision',
            name='cod_prod',
        ),
    ]
