# Generated by Django 5.2 on 2025-06-19 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmisionesApp', '0003_remove_emision_cod_prod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emision',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Solicitud Cancelada'),
        ),
        migrations.AddField(
            model_name='emision',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelacion'),
        ),
        migrations.AddField(
            model_name='emision',
            name='usuario_cancelación',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelar_emisiones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Cancelador'),
        ),
    ]
