# Generated by Django 5.2 on 2025-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmisionesApp', '0004_emision_cancelada_emision_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emision',
            name='notas_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de cancelación'),
        ),
    ]
