# Generated by Django 5.2 on 2025-06-20 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmisionesApp', '0005_emision_notas_cancelacion'),
        ('ProductorApp', '0003_codigoproductor_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='poliza',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Poliza Activa'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='cant_cuotas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de cuotas'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='rel_cod_prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProductorApp.codigoproductor', verbose_name='Código de Productor'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='vencimiento_cuota1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencmiento 1er cupón'),
        ),
        migrations.CreateModel(
            name='Endoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('numero', models.IntegerField(verbose_name='Número de endoso')),
                ('tipo', models.CharField(choices=[('A', 'Alta'), ('M', 'Modificación'), ('B', 'Anulación'), ('R', 'Rehabilitacion')], max_length=1, verbose_name='Tipo de endoso')),
                ('vigencia_desde', models.DateTimeField(verbose_name='Comienzo de vigencia')),
                ('vigencia_hasta', models.DateTimeField(verbose_name='Fin de vigencia')),
                ('prima', models.FloatField(verbose_name='Prima')),
                ('premio', models.FloatField(verbose_name='Prima')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo del endoso')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmisionesApp.poliza', verbose_name='Endoso')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nueva_poliza', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
        ),
    ]
