# Generated by Django 5.2 on 2025-06-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0003_mediopago_tarjetacredito_transferenciabancaria'),
        ('EmisionesApp', '0006_remove_poliza_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='rel_medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClientesApp.mediopago', verbose_name='Medio de Pago'),
        ),
    ]
