# Generated by Django 5.2 on 2025-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmisionesApp', '0007_alter_poliza_rel_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cant_endosos',
            field=models.IntegerField(default=0, verbose_name='Cantidad de endosos'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='pol_previa',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Poliza Previa'),
        ),
    ]
