# Generated by Django 5.2 on 2025-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmisionesApp', '0008_poliza_cant_endosos_poliza_pol_previa'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='renovable',
            field=models.BooleanField(default=True, verbose_name='Póliza Renovable'),
        ),
    ]
