# Generated by Django 5.2 on 2025-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmisionesApp', '0009_poliza_renovable'),
    ]

    operations = [
        migrations.AddField(
            model_name='emision',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
