# Generated by Django 5.2 on 2025-07-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmisionesApp', '0010_emision_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'En relevamiento'), ('V', 'Resuelto Via Voucher'), ('I', 'Informado a Compañía'), ('A', 'Aceptado por Compañía'), ('R', 'Resuelto'), ('F', 'Finalizado conforme'), ('X', 'Rechazado por la compañía')], default='P', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ocurrencia', models.DateTimeField(verbose_name='Fecha y hora de ocurrencia del siniestro')),
                ('lugar', models.CharField(max_length=120, verbose_name='Lugar de ocurrencia del siniestro')),
                ('descripcion', models.TextField(verbose_name='Descripción del siniestro')),
                ('denunciado', models.BooleanField(default=False, verbose_name='Con denuncia pollicial')),
                ('terc', models.CharField(choices=[('N', 'Sin terceros involucrados'), ('R', 'Tercero Responsable'), ('D', 'Tercero Damnificado')], default='N', max_length=1)),
                ('danios', models.TextField(blank=True, null=True, verbose_name='Descripción de los daños propios')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de seguimiento')),
                ('fecha_voucher', models.DateField(blank=True, null=True, verbose_name='Fecha de generación de Voucher')),
                ('nro_voucher', models.CharField(blank=True, max_length=18, null=True, verbose_name='Nro de Voucher')),
                ('fecha_informe', models.DateField(blank=True, null=True, verbose_name='Fecha de informe de siniestro a la cía')),
                ('nro_siniestro', models.CharField(blank=True, max_length=18, null=True, verbose_name='Nro de siniestro')),
                ('liquidador_nombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre del liquidador')),
                ('liquidador_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del liquidador')),
                ('liquidador_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail del liquidador')),
                ('inspec_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de inspección')),
                ('inspec_lugar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lugar de la inspección')),
                ('taller', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taller o servicio técnico asignado')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de informe de resolución de siniestro')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre de sinistro')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmisionesApp.poliza', verbose_name='Póliza')),
            ],
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Tercero')),
                ('dni', models.CharField(blank=True, max_length=12, null=True, verbose_name='DNI del Tercero')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono del Tercero')),
                ('mail', models.EmailField(blank=True, max_length=25, null=True, verbose_name='mail del Tercero')),
                ('nro_poliza', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de póliza del Tercero')),
                ('compania', models.CharField(blank=True, max_length=20, null=True, verbose_name='Aseguradora del Tercero')),
                ('bien_afectado', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bien del tercero afectado por el siniestro')),
                ('danios', models.TextField(blank=True, null=True, verbose_name='Descripción de los daños al tercer')),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiniestrosApp.siniestro', verbose_name='Siniestro')),
            ],
        ),
    ]
