# Generated by Django 5.2 on 2025-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiniestrosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siniestro',
            name='fecha_cierre',
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='status',
            field=models.CharField(choices=[('P', 'En relevamiento'), ('I', 'Informado a Compañía'), ('R', 'Resuelto'), ('V', 'Resuelto Via Voucher'), ('X', 'Rechazado por la compañía')], default='P', max_length=1),
        ),
    ]
