# Generated by Django 5.2 on 2025-07-03 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiniestrosApp', '0002_remove_siniestro_fecha_cierre_alter_siniestro_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='siniestros/', verbose_name='Archivos asociados a siniestros')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripción del Archivo')),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiniestrosApp.siniestro', verbose_name='Emisión')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_siniestro_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
        ),
    ]
