# Generated by Django 5.2 on 2025-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiniestrosApp', '0003_docsiniestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='cobertura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de cobertura de la poliza'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='franquicia_fija',
            field=models.FloatField(blank=True, null=True, verbose_name='Franquicia Fija'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='porc_franquicia',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje Franquicia'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='short_desc',
            field=models.CharField(default='Siniestro', max_length=20, verbose_name='Descripcion corta del sinistro'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='suma_aseg',
            field=models.FloatField(blank=True, null=True, verbose_name='Suma asegurada'),
        ),
    ]
