# Generated by Django 5.2 on 2025-07-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiniestrosApp', '0004_siniestro_cobertura_siniestro_franquicia_fija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='causa_no_reclammo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Causa de no generacion de reclamo a terceros'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='reclamo_ter',
            field=models.BooleanField(default=False, verbose_name='Tiene reclamo terceros'),
        ),
    ]
