# Generated by Django 5.2 on 2025-05-23 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiaMailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=50, verbose_name='Mail')),
                ('contacto', models.CharField(max_length=50, verbose_name='Contacto')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción del contacto')),
            ],
            options={
                'verbose_name': 'mail de Contacto',
                'verbose_name_plural': 'Mails de contacto',
            },
        ),
        migrations.CreateModel(
            name='CiaTelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('contacto', models.CharField(max_length=50, verbose_name='Contacto')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción del contacto')),
            ],
            options={
                'verbose_name': 'teléfono de Contacto',
                'verbose_name_plural': 'Teléfonos de contacto',
            },
        ),
        migrations.CreateModel(
            name='Cia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la compañía')),
                ('logoUrl', models.CharField(blank=True, null=True, verbose_name='URL del logo de la compañía')),
                ('cuit', models.CharField(max_length=15, verbose_name='CUIT de la compañía')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descripción de la compañía')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.address', verbose_name='Dirección de la compañía')),
                ('mailContact', models.ManyToManyField(blank=True, to='AseguradoraApp.ciamailcontact', verbose_name='Mails de contacto')),
                ('telContact', models.ManyToManyField(blank=True, to='AseguradoraApp.ciatelcontact', verbose_name='Teléfonos de contacto')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
            },
        ),
    ]
