# Generated by Django 5.2 on 2025-05-24 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AseguradoraApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cia',
            name='mailContact',
        ),
        migrations.RemoveField(
            model_name='cia',
            name='telContact',
        ),
        migrations.AddField(
            model_name='ciamailcontact',
            name='cia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AseguradoraApp.cia', verbose_name='Compañía'),
        ),
        migrations.AddField(
            model_name='ciatelcontact',
            name='cia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AseguradoraApp.cia', verbose_name='Compañía'),
        ),
    ]
