# Generated by Django 5.2 on 2025-05-24 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AseguradoraApp', '0002_remove_cia_mailcontact_remove_cia_telcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cia',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Compañía activa'),
        ),
        migrations.AlterField(
            model_name='ciamailcontact',
            name='cia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AseguradoraApp.cia', verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='ciatelcontact',
            name='cia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AseguradoraApp.cia', verbose_name='Compañía'),
        ),
    ]
