# Generated by Django 5.2 on 2025-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AseguradoraApp', '0003_cia_activa_alter_ciamailcontact_cia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cia',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL de la compañía'),
        ),
    ]
