# Generated by Django 5.2 on 2025-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AseguradoraApp', '0004_cia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cia',
            name='ciaid',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='ID de la compañía'),
        ),
    ]
