# Generated by Django 5.2 on 2025-06-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AseguradoraApp', '0005_cia_ciaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cia',
            name='ciaid',
            field=models.CharField(max_length=4, verbose_name='ID de la compañía'),
        ),
    ]
