# Generated by Django 5.2 on 2025-05-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rubro')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rubro de Prestador',
                'verbose_name_plural': 'Rubros de Prestadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Prestador')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffApp.rubroprestador', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['rubro__nombre', 'nombre'],
            },
        ),
    ]
