# Generated by Django 5.2 on 2025-05-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0002_rubroprestador_prestador'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
    ]
