# Generated by Django 5.2 on 2025-05-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributo'), ('EX', 'Exento'), ('NR', 'No Responsable'), ('CF', 'Consumidor Final')], max_length=2)),
                ('notas', models.TextField(blank=True)),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoCte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePersonaFisica',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ClientesApp.cliente')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
            bases=('ClientesApp.cliente',),
        ),
        migrations.CreateModel(
            name='ClientePersonaJuridica',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ClientesApp.cliente')),
                ('razon_social', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=20)),
            ],
            bases=('ClientesApp.cliente',),
        ),
        migrations.AddField(
            model_name='cliente',
            name='emails',
            field=models.ManyToManyField(blank=True, to='ClientesApp.emailcte'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefonos',
            field=models.ManyToManyField(blank=True, to='ClientesApp.telefonocte'),
        ),
    ]
