# Generated by Django 5.2 on 2025-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepersonafisica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
