# Generated by Django 5.2 on 2025-06-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0002_alter_clientepersonafisica_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TC', 'Tarjeta de Crédito'), ('TB', 'Transferencia Bancaria')], max_length=2)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='ClientesApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('mediopago_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ClientesApp.mediopago')),
                ('tarjeta', models.CharField(max_length=30)),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('titular', models.CharField(max_length=100)),
                ('vencimiento', models.CharField(max_length=5)),
            ],
            bases=('ClientesApp.mediopago',),
        ),
        migrations.CreateModel(
            name='TransferenciaBancaria',
            fields=[
                ('mediopago_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ClientesApp.mediopago')),
                ('cbu', models.CharField(max_length=20)),
                ('titular_cuenta', models.CharField(max_length=100)),
            ],
            bases=('ClientesApp.mediopago',),
        ),
    ]
