# Generated by Django 5.2 on 2025-06-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AseguradoraApp', '0004_cia_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributo'), ('EX', 'Exento'), ('NR', 'No Responsable'), ('CF', 'Consumidor Final')], default='MO', max_length=2)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoProductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AseguradoraApp.cia')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_productor', to='ProductorApp.productor')),
            ],
            options={
                'verbose_name': 'Código de Productor',
                'verbose_name_plural': 'Códigos de Productores',
            },
        ),
    ]
