# Generated by Django 5.2 on 2025-06-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoproductor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
