# Generated by Django 5.2 on 2025-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductorApp', '0002_codigoproductor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoproductor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
