# Generated by Django 5.2 on 2025-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std_Automotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Automotor'), ('M', 'Moto')], default='A', max_length=1, verbose_name='Tipo de Automotor')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Automotor',
                'verbose_name_plural': 'Automotores',
            },
        ),
    ]
