# Generated by Django 5.2 on 2025-06-11 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0003_mediopago_tarjetacredito_transferenciabancaria'),
        ('CotizacionesApp', '0001_initial'),
        ('RubrosApp', '0002_remove_rubrocat_imagen_alter_categoria_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dato', models.CharField(max_length=50, verbose_name='Nombre del dato')),
                ('tipo_dato', models.CharField(choices=[('T', 'Texto'), ('N', '´Número'), ('B', 'Booleano'), ('C', 'Choice')], max_length=1)),
                ('mandatorio', models.BooleanField()),
                ('choices', models.CharField(max_length=150)),
                ('help_text', models.CharField(blank=True, max_length=250, null=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RubrosApp.categoria', verbose_name='Rubro')),
            ],
        ),
        migrations.CreateModel(
            name='QuotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('F', 'Cotizada'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Estado')),
                ('detalle', models.TextField(verbose_name='Detalle a cotizar')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClientesApp.cliente')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RubrosApp.categoria', verbose_name='Rubro')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('usuario_finalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Finalización')),
            ],
        ),
        migrations.DeleteModel(
            name='Std_Automotor',
        ),
    ]
