# Generated by Django 5.2 on 2025-06-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0002_datacotizacion_quotrequest_delete_std_automotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacotizacion',
            name='choices',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
