# Generated by Django 5.2 on 2025-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0003_alter_datacotizacion_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotrequest',
            name='notas_finalización',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
