# Generated by Django 5.2 on 2025-06-13 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0003_mediopago_tarjetacredito_transferenciabancaria'),
        ('CotizacionesApp', '0004_quotrequest_notas_finalización'),
        ('RubrosApp', '0002_remove_rubrocat_imagen_alter_categoria_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sujeto', models.TextField(verbose_name='Detalle a cotizar')),
                ('status', models.CharField(choices=[('P', 'En Preparación'), ('E', 'Enviada al cliente'), ('S', 'Solicitada Emisión'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envio al cliente')),
                ('detalles_envio', models.TextField(blank=True, null=True, verbose_name='Notas de envio')),
                ('fecha_sol_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de solicitud emisión')),
                ('detalles_sol_emision', models.TextField(blank=True, null=True, verbose_name='Notas de solicitud de emision')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelacion')),
                ('notas_cancelacion', models.TextField(blank=True, null=True, verbose_name='Notas de cancelacion de cotizacion')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClientesApp.cliente')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RubrosApp.categoria', verbose_name='Rubro')),
                ('solicitud_cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CotizacionesApp.quotrequest', verbose_name='Solicitud de Cotizacion')),
                ('usuario_cancelacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancela_cotizacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Finalización')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuevas_cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('usuario_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario envio')),
                ('usuario_sol_emision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_emision', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitud de emision')),
            ],
        ),
    ]
