# Generated by Django 5.2 on 2025-06-13 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AseguradoraApp', '0004_cia_url'),
        ('CotizacionesApp', '0005_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionCia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fechas de cotización')),
                ('premio', models.FloatField(verbose_name='Premio en pesos')),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AseguradoraApp.cia', verbose_name='Compañia Aseguradora')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CotizacionesApp.cotizacion', verbose_name='cotización')),
            ],
        ),
    ]
