# Generated by Django 5.2 on 2025-06-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0006_cotizacioncia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciónes'},
        ),
        migrations.AlterModelOptions(
            name='quotrequest',
            options={'verbose_name': 'Solicitud de Cotización', 'verbose_name_plural': 'Solicitudes de Cotización'},
        ),
    ]
