# Generated by Django 5.2 on 2025-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0007_alter_cotizacion_options_alter_quotrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_aceptacion',
            field=models.FileField(blank=True, null=True, upload_to='aceptaciones/', verbose_name='Archivo de aceptación del cliente'),
        ),
    ]
