# Generated by Django 5.2 on 2025-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0008_cotizacion_archivo_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncia',
            name='cobertura',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo de cobertura (TR, TC, etc...)'),
        ),
    ]
