# Generated by Django 5.2 on 2025-06-16 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0009_cotizacioncia_cobertura'),
        ('RubrosApp', '0002_remove_rubrocat_imagen_alter_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30, verbose_name='Nombre del dato')),
                ('requerido', models.BooleanField(verbose_name='Es dato obligatorio')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RubrosApp.categoria', verbose_name='Rubro')),
            ],
        ),
    ]
