# Generated by Django 5.2 on 2025-06-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0010_dataemision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='archivo_aceptacion',
        ),
    ]
