# Generated by Django 5.2 on 2025-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0011_remove_cotizacion_archivo_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotrequest',
            name='extradata',
            field=models.TextField(blank=True, null=True, verbose_name='Datos extra sobre el riesgo'),
        ),
        migrations.AlterField(
            model_name='datacotizacion',
            name='choices',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotrequest',
            name='detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle a cotizar'),
        ),
    ]
