# Generated by Django 5.2 on 2025-06-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0012_quotrequest_extradata_alter_datacotizacion_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='sujeto',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='extradata',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle extra de Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='solicitud_cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CotizacionesApp.quotrequest', verbose_name='Solicitud de Cotizacion'),
        ),
    ]
