# Generated by Django 5.2 on 2025-06-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CotizacionesApp', '0013_remove_cotizacion_sujeto_cotizacion_extradata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncia',
            name='prima',
            field=models.FloatField(default=0.0, verbose_name='Prima en pesos'),
        ),
    ]
